[package]
name = "metronome"
version = "2.1.0"
edition = "2021"
authors = ["Peter Steneld"]

[dependencies]
rodio = { version = "0.19", default-features = false, features = ["wav"] }
clap = { version = "4", features = ["derive"]}
