[package]
name = "metronome"
version = "1.1.0"
edition = "2021"
authors = ["Peter Steneld"]
description = "Metronome for speed training on the guitar"

[dependencies]
rodio = { version = "0.19", default-features = false, features = ["wav"] }
clap = { version = "4", features = ["derive"]}
