[package]
name = "metronome"
version = "0.1.0"
edition = "2021"
authors = ["Peter Steneld"]
description = "Metronome for speed training on the guitar"

[dependencies]
rodio = "0.19"
clap = { version = "4", features = ["derive"]}
